/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.orderapp;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFpbCvEa7agMw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFpbCvEa7agMw= >>
// ----------- >>
public class CAMERIERE extends UTENTE {
    // ----------- << method.annotations@AAAAAAGFpbLNca9fip4= >>
    // ----------- >>
    public void NuovoOrdine() {
    // ----------- << method.body@AAAAAAGFpbLNca9fip4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFpbL8IK9mDdk= >>
    // ----------- >>
    public void CancellaOrdine() {
    // ----------- << method.body@AAAAAAGFpbL8IK9mDdk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFpbMNG69tTCQ= >>
    // ----------- >>
    public void NuovaPrenotazione() {
    // ----------- << method.body@AAAAAAGFpbMNG69tTCQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFpbMqu690uMA= >>
    // ----------- >>
    public void CancellaPrenotazione() {
    // ----------- << method.body@AAAAAAGFpbMqu690uMA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFpnkvHHdwfPA= >>
    // ----------- >>
    public void CheckPrenotazione() {
    // ----------- << method.body@AAAAAAGFpnkvHHdwfPA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFpz2fEWlzoNY= >>
    // ----------- >>
    public void ModificaOrdine() {
    // ----------- << method.body@AAAAAAGFpz2fEWlzoNY= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFpz3NMGn+RsA= >>
    // ----------- >>
    public void ModificaPrenotazione() {
    // ----------- << method.body@AAAAAAGFpz3NMGn+RsA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFr6KspYvb8fc= >>
    // ----------- >>
    public void VisualizzaPrenotazione() {
    // ----------- << method.body@AAAAAAGFr6KspYvb8fc= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGFpbCvEa7agMw= >>
// ----------- >>
}