/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.orderapp;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFpbDQ3q8ED+w= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFpbDQ3q8ED+w= >>
// ----------- >>
public class CUOCO extends UTENTE {
    // ----------- << method.annotations@AAAAAAGFpbOBma+ESz0= >>
    // ----------- >>
    public void CheckOrdine() {
    // ----------- << method.body@AAAAAAGFpbOBma+ESz0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFq37NaMi67Fk= >>
    // ----------- >>
    public void checkOrdine() {
    // ----------- << method.body@AAAAAAGFq37NaMi67Fk= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGFpbDQ3q8ED+w= >>
// ----------- >>
}