/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.orderapp;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFpbRZgK+L+Sc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFpbRZgK+L+Sc= >>
// ----------- >>
public class ORDINE {
    // ----------- << attribute.annotations@AAAAAAGFpcYG5M0miSQ= >>
    // ----------- >>
    private int id;

    // ----------- << attribute.annotations@AAAAAAGFq3W6Jav3sYQ= >>
    // ----------- >>
    private String stato;

    // ----------- << attribute.annotations@AAAAAAGFq6EvztfEU8s= >>
    // ----------- >>
    private float prezzo;

    public int getId() {
        return id;
    }

    public String getStato() {
        return this.stato;
    }

    public float getPrezzo() {
        return this.prezzo;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setStato(String stato) {
        this.stato = stato;
    }

    public void setPrezzo(float prezzo) {
        this.prezzo= prezzo;
    }

    // ----------- << method.annotations@AAAAAAGFq3yzfr8vE8s= >>
    // ----------- >>
    public void setStato() {
    // ----------- << method.body@AAAAAAGFq3yzfr8vE8s= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFq3zaVr/bCB0= >>
    // ----------- >>
    public void setId() {
    // ----------- << method.body@AAAAAAGFq3zaVr/bCB0= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFq3z2l8EstxI= >>
    // ----------- >>
    public void MostraStato() {
    // ----------- << method.body@AAAAAAGFq3z2l8EstxI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGFpbRZgK+L+Sc= >>
// ----------- >>
}