/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.orderapp;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFp1t4DQDOnP0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFp1t4DQDOnP0= >>
// ----------- >>
public class PRENOTAZIONE {
    // ----------- << attribute.annotations@AAAAAAGFp1uviAY6/3M= >>
    // ----------- >>
    private String nome;

    // ----------- << attribute.annotations@AAAAAAGFp1vQegbFSBw= >>
    // ----------- >>
    private String numTelefono;

    // ----------- << attribute.annotations@AAAAAAGFp9htC0q3H0Y= >>
    // ----------- >>
    private String id;

    // ----------- << attribute.annotations@AAAAAAGFq3V7lalVem8= >>
    // ----------- >>
    private String stato;

    public String getNome() {
        return this.nome;
    }

    public String getNumTelefono() {
        return this.numTelefono;
    }

    public String getId() {
        return this.id;
    }

    public String getStato() {
        return this.stato;
    }

    public void setNome(String nome) {
        this.nome= nome;
    }

    public void setNumTelefono(String numTelefono) {
        this.numTelefono = numTelefono;
    }

    public void setId(String id) {
        this.id= id;
    }

    public void setStato(String stato) {
        this.stato= stato;
    }

    public String MostraDati() {
        return this.id + this.nome + this.numTelefono + this.stato;
    }
// ----------- << class.extras@AAAAAAGFp1t4DQDOnP0= >>
// ----------- >>
}