/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.orderapp;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFpbRxFq+1q5w= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFpbRxFq+1q5w= >>
// ----------- >>
public class TAVOLO {
    // ----------- << attribute.annotations@AAAAAAGFpbZvgLEV0Is= >>
    // ----------- >>
    private int numero;

    // ----------- << attribute.annotations@AAAAAAGFq3Wk7Kqmv3A= >>
    // ----------- >>
    private String stato;

    public int getNumero() {
        return numero;
    }

    public String getStato() {
        return stato;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public void setStato(String stato) {
        this.stato = stato;
    }

    // ----------- << method.annotations@AAAAAAGFq4AXHNCjHng= >>
    // ----------- >>
    public void setStato() {
    // ----------- << method.body@AAAAAAGFq4AXHNCjHng= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGFr6hpIZKKXGs= >>
    // ----------- >>
    public void MostraDati() {
    // ----------- << method.body@AAAAAAGFr6hpIZKKXGs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGFpbRxFq+1q5w= >>
// ----------- >>
}