/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.orderapp;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFpbCWx66wqbs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFpbCWx66wqbs= >>
// ----------- >>
public abstract class UTENTE {
    // ----------- << method.annotations@AAAAAAGFpbHtN69R5pE= >>
    // ----------- >>
    public ORDINE VisualizzaOrdine() {

    }
// ----------- << class.extras@AAAAAAGFpbCWx66wqbs= >>
// ----------- >>
}