/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.example.orderapp;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGFpbTlGrAN9Zw= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGFpbTlGrAN9Zw= >>
// ----------- >>
public class CLIENTE {
    // ----------- << attribute.annotations@AAAAAAGFpbUGC7A3suw= >>
    // ----------- >>
    private String Nome;

    // ----------- << attribute.annotations@AAAAAAGFpbUbsLA+1lg= >>
    // ----------- >>
    private String Cognome;

    public String getNome() {
        return Nome;
    }

    public String getCognome() {
        return Cognome;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public void setCognome(String Cognome) {
        this.Cognome = Cognome;
    }

// ----------- << class.extras@AAAAAAGFpbTlGrAN9Zw= >>
// ----------- >>
}